<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.COVRCGO' shared service.

return $this->privates['.service_locator.COVRCGO'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('account' => function (): \App\Entity\Account {
    return ($this->privates['.errored..service_locator.COVRCGO.App\Entity\Account'] ?? $this->load('getAccountService.php'));
}, 'em' => function () {
    return ($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php'));
}));
