<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.m3hBeYH.App\Entity\Transaction' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.m3hBeYH": it references class "App\\Entity\\Transaction" but no such service exists.');
