<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\AccountController::addBeneficiary' => function () {
    return ($this->privates['.service_locator.COVRCGO'] ?? $this->load('get_ServiceLocator_COVRCGOService.php'));
}, 'App\\Controller\\AccountController::create' => function () {
    return ($this->privates['.service_locator.v_q6gfB'] ?? $this->load('get_ServiceLocator_VQ6gfBService.php'));
}, 'App\\Controller\\AccountController::delete' => function () {
    return ($this->privates['.service_locator.COVRCGO'] ?? $this->load('get_ServiceLocator_COVRCGOService.php'));
}, 'App\\Controller\\AccountController::deleteBeneficiary' => function () {
    return ($this->privates['.service_locator.zWN.8YM'] ?? $this->load('get_ServiceLocator_ZWN_8YMService.php'));
}, 'App\\Controller\\AccountController::list' => function () {
    return ($this->privates['.service_locator.eNuPrwI'] ?? $this->load('get_ServiceLocator_ENuPrwIService.php'));
}, 'App\\Controller\\AccountController::modify' => function () {
    return ($this->privates['.service_locator.COVRCGO'] ?? $this->load('get_ServiceLocator_COVRCGOService.php'));
}, 'App\\Controller\\AccountController::showTransactions' => function () {
    return ($this->privates['.service_locator.tDNu2os'] ?? $this->load('get_ServiceLocator_TDNu2osService.php'));
}, 'App\\Controller\\TransactionController::create' => function () {
    return ($this->privates['.service_locator.v_q6gfB'] ?? $this->load('get_ServiceLocator_VQ6gfBService.php'));
}, 'App\\Controller\\TransactionController::delete' => function () {
    return ($this->privates['.service_locator.m3hBeYH'] ?? $this->load('get_ServiceLocator_M3hBeYHService.php'));
}, 'App\\Controller\\TransactionController::list' => function () {
    return ($this->privates['.service_locator.6Ep6P_t'] ?? $this->load('get_ServiceLocator_6Ep6PTService.php'));
}, 'App\\Controller\\TransactionController::payBeneficiary' => function () {
    return ($this->privates['.service_locator.zWN.8YM'] ?? $this->load('get_ServiceLocator_ZWN_8YMService.php'));
}, 'App\\Controller\\AccountController:addBeneficiary' => function () {
    return ($this->privates['.service_locator.COVRCGO'] ?? $this->load('get_ServiceLocator_COVRCGOService.php'));
}, 'App\\Controller\\AccountController:create' => function () {
    return ($this->privates['.service_locator.v_q6gfB'] ?? $this->load('get_ServiceLocator_VQ6gfBService.php'));
}, 'App\\Controller\\AccountController:delete' => function () {
    return ($this->privates['.service_locator.COVRCGO'] ?? $this->load('get_ServiceLocator_COVRCGOService.php'));
}, 'App\\Controller\\AccountController:deleteBeneficiary' => function () {
    return ($this->privates['.service_locator.zWN.8YM'] ?? $this->load('get_ServiceLocator_ZWN_8YMService.php'));
}, 'App\\Controller\\AccountController:list' => function () {
    return ($this->privates['.service_locator.eNuPrwI'] ?? $this->load('get_ServiceLocator_ENuPrwIService.php'));
}, 'App\\Controller\\AccountController:modify' => function () {
    return ($this->privates['.service_locator.COVRCGO'] ?? $this->load('get_ServiceLocator_COVRCGOService.php'));
}, 'App\\Controller\\AccountController:showTransactions' => function () {
    return ($this->privates['.service_locator.tDNu2os'] ?? $this->load('get_ServiceLocator_TDNu2osService.php'));
}, 'App\\Controller\\TransactionController:create' => function () {
    return ($this->privates['.service_locator.v_q6gfB'] ?? $this->load('get_ServiceLocator_VQ6gfBService.php'));
}, 'App\\Controller\\TransactionController:delete' => function () {
    return ($this->privates['.service_locator.m3hBeYH'] ?? $this->load('get_ServiceLocator_M3hBeYHService.php'));
}, 'App\\Controller\\TransactionController:list' => function () {
    return ($this->privates['.service_locator.6Ep6P_t'] ?? $this->load('get_ServiceLocator_6Ep6PTService.php'));
}, 'App\\Controller\\TransactionController:payBeneficiary' => function () {
    return ($this->privates['.service_locator.zWN.8YM'] ?? $this->load('get_ServiceLocator_ZWN_8YMService.php'));
}))), ($this->privates['debug.stopwatch'] ?? $this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true)));
