<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.COVRCGO.App\Entity\Account' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.COVRCGO": it references class "App\\Entity\\Account" but no such service exists.');
