<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKavbh19\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKavbh19/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKavbh19.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKavbh19\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerKavbh19\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Kavbh19',
    'container.build_id' => '35934688',
    'container.build_time' => 1538055452,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerKavbh19');
