<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMvXsZe3\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMvXsZe3/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMvXsZe3.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMvXsZe3\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerMvXsZe3\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'MvXsZe3',
    'container.build_id' => '9fe49222',
    'container.build_time' => 1538038067,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerMvXsZe3');
