<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIuxNxKv\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIuxNxKv/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIuxNxKv.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIuxNxKv\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerIuxNxKv\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'IuxNxKv',
    'container.build_id' => '83b5c531',
    'container.build_time' => 1538058787,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerIuxNxKv');
